POSSIBLE_REPORTS = [
    "IPCC AR6 WGI SPM",
    "IPCC AR6 WGI FR",
    "IPCC AR6 WGI TS",
    "IPCC AR6 WGII SPM",
    "IPCC AR6 WGII TS",
    "IPCC AR6 WGII FR",
    "IPCC AR6 WGIII SPM",
    "IPCC AR6 WGIII TS",
    "IPCC AR6 WGIII FR",
    "IPCC AR6 SYR",
    "IPCC SR GW SPM",
    "IPCC SR CCL SPM",
    "IPCC SR OC SPM",
    "IPCC SR OC TS",
    "IPCC SR OC C1",
    "IPCC SR OC C2",
    "IPCC SR OC C3",
    "IPCC SR OC C4",
    "IPCC SR OC C5",
    "IPCC SR OC C6",
    "IPCC SR OC CC B9",
    "IPCC SR OC A1 G",
    "IPBES GAR FR",
    "IPBES GAR SPM",
    "IPBES TAM SW FR",
    "IPBES TAM SW SPM",
    "IPBES RAR AF FR",
    "IPBES RAR AF SPM",
    "IPBES RAR AM FR",
    "IPBES RAR AM SPM",
    "IPBES RAR AP FR",
    "IPBES RAR AP SPM",
    "IPBES RAR ECA FR",
    "IPBES RAR ECA SPM",
    "IPBES AR LDR FR",
    "IPBES AR LDR SPM",
    "IPBES IAS A C1",
    "IPBES IAS A C2",
    "IPBES IAS A C3",
    "IPBES IAS A C4",
    "IPBES IAS A C5",
    "IPBES IAS A C6",
    "IPBES IAS A SPM"
]

OWID_CATEGORIES = ['Access to Energy', 'Agricultural Production',
       'Agricultural Regulation & Policy', 'Air Pollution',
       'Animal Welfare', 'Antibiotics', 'Biodiversity', 'Biofuels',
       'Biological & Chemical Weapons', 'CO2 & Greenhouse Gas Emissions',
       'COVID-19', 'Clean Water', 'Clean Water & Sanitation',
       'Climate Change', 'Crop Yields', 'Diet Compositions',
       'Electricity', 'Electricity Mix', 'Energy', 'Energy Efficiency',
       'Energy Prices', 'Environmental Impacts of Food Production',
       'Environmental Protection & Regulation', 'Famines', 'Farm Size',
       'Fertilizers', 'Fish & Overfishing', 'Food Supply', 'Food Trade',
       'Food Waste', 'Food and Agriculture', 'Forests & Deforestation',
       'Fossil Fuels', 'Future Population Growth',
       'Hunger & Undernourishment', 'Indoor Air Pollution', 'Land Use',
       'Land Use & Yields in Agriculture', 'Lead Pollution',
       'Meat & Dairy Production', 'Metals & Minerals',
       'Natural Disasters', 'Nuclear Energy', 'Nuclear Weapons',
       'Oil Spills', 'Outdoor Air Pollution', 'Ozone Layer', 'Pandemics',
       'Pesticides', 'Plastic Pollution', 'Renewable Energy', 'Soil',
       'Transport', 'Urbanization', 'Waste Management', 'Water Pollution',
       'Water Use & Stress', 'Wildfires']